version: "2"

services:
  caliper_2.1:
    container_name: caliper_2.1
    image: hyperledger/caliper:0.4.2
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=chaincodes/real_estate/benchmarks/config.yaml
      - CALIPER_NETWORKCONFIG=networks/config.yaml
    volumes:
      - .:/hyperledger/caliper/workspace
    network_mode: host